---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: infras-go-service
  namespace: devops
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  releaseName: infras-go-service
  chart:
    git: git@github.com:pmquang/infras-flux-demo.git
    ref: master
    path: charts/common-service
  values:
    schedulerName: default-scheduler
    image:
      repository: 922326500294.dkr.ecr.ap-southeast-1.amazonaws.com/backend/infras-go-service
      tag: 1.0.0
    ingress:
      class: external-nginx-ingress
      enabled: true
      hosts:
      - infras-go-service.example.com
    initialDelaySeconds: 60
    jaeger:
      enabled: false
    minReadySeconds: 5
    hpa:
      autoscaling:
        minReplicas: 3
        maxReplicas: 10
        enabled: true
        averageCPUUtilization: 50
    resources:
      limits:
        cpu: 700m
        memory: 1024Mi
      requests:
        cpu: 300m
        memory: 512Mi
    healthcheck:
      method: tcp
    secret:
    - name: bar
      value: foo
    service:
      externalPort: 80
      internalPort: 9000
