---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: devops
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: metrics-server
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.9.0
  values:
    image:
      repository: gcr.io/google_containers/metrics-server-amd64
      tag: v0.3.6
      pullPolicy: IfNotPresent
