---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-nginx-ingress
  namespace: devops
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: external-nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.30.1
  values:
    controller:
      service:
        type: LoadBalancer
        targetPorts:
          http: http
          https: https
      ingressClass: external-nginx-ingress
      image:
        repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
        tag: "0.28.0"
        pullPolicy: IfNotPresent
      replicaCount: 3
      resources:
        limits:
          cpu: 100m
          memory: 1000Mi
        requests:
          cpu: 100m
          memory: 1000Mi
