{{- if .Values.configFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common-service.fullname" . }}
  labels:
    app: {{ template "common-service.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.image.tag | quote }}
    brand: {{ .Release.Namespace }}
    tier: {{ .Values.tier | default "backend" }}
data:
  {{- range $fileName, $fileAttr := .Values.configFiles }}
  {{ $fileName }}:
{{ toYaml $fileAttr.content | indent 4 }}
  {{- end }}
{{- end }}
