{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common-service.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ range .Values.secret }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- end }}

---

{{ if .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
data:
  .dockercfg: {{ .Values.imagePullSecrets }}
type: kubernetes.io/dockercfg
metadata:
  name: {{ template "common-service.fullname" . }}-pullsecret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ end }}
